### ISSUE TITLE
Not being able to view jobs

### ISSUE THREAD

**Issue by randomboy101** [midas-research/audino#128]
<img width="1350" alt="Screenshot 2024-01-31 at 4 41 44 PM" src="https://github.com/midas-research/audino/assets/158281482/59e4b59d-b5cf-4313-a237-3c078f648f9a">

Hi, I have uploaded a few tasks, and audino was able to create jobs for them, but i am not able to view the jobs. Kindly look into it, Thanks!

**Comment by rohan220217** [comment]
Hi @randomboy101 sorry for replying late but we have deployed our frontend with cvat backend and it is stable now.

**Comment by rohan220217** [comment]
@hayderkharrufa Are you using it on your local machine or the deployed one - app.audino.in ?
