### ISSUE TITLE
How to properly configure v2 prod 

### ISSUE THREAD

**Issue by chriskathumbi** [midas-research/audino#130]
Hello, I'm trying to set up v2 and I get an authentication error when making projects.
I tried login in on admin but I don't know the admin password or whether it exists on the database.
There seems to be some mixing of info from v1 on v2

**Comment by rohan220217** [comment]
Hi @chriskathumbi sorry for the late reply but we have updated the v2 you can try it now.

**Comment by chriskathumbi** [comment]
Hello, new push gets hit as malware on
![image](https://github.com/user-attachments/assets/1e94a54a-9ff6-4145-8ad7-034c7ffd588d)
