### ISSUE TITLE
Unable to do the example request as part of the documentation

### ISSUE THREAD

**Issue by nickx720** [midas-research/audino#33]
Hi ,
    I have cloned the project and ran it, but when I am trying to execute the example upload I get an invalid syntax problem from the attached python script upload_data.py. Not sure if I am doing something wrong here, I have also tried to send the request via Postman but I am unclear as to how to send a .wav file along with username credentials in the same JSON file.

![image](https://user-images.githubusercontent.com/34407800/84524740-5953df80-acd2-11ea-94f9-e2b396bb807c.png)

**Comment by manrajgrover** [comment]
Hi @nickx720,

Kindly share the python version you're using.

**Comment by nickx720** [comment]
Hi @manrajgrover,

Thanks for your reply. I am using Python 2.7.16.

**Comment by manrajgrover** [comment]
The script is written for Python 3 (Python 3.7 to be specific). You would need to modify it for Python 2.

**Comment by nickx720** [comment]
Thanks @manrajgrover. It works fine now. Cheers
