### ISSUE TITLE
http://0.0.0.0/ is a default idex.html for nginx

### ISSUE THREAD

**Issue by anu308** [midas-research/audino#36]
I ran docker-compose -f docker-compose.prod.yml up with 7000 port for nginx instead of 80 as it was being used by some other process.
I get welcome to nginx page instead of audino dasboard.
and my console output as below,

Creating network "audino_default" with the default driver
Creating network "audino_backend-network" with the default driver
Creating network "audino_frontend-network" with the default driver
Creating audino_mysql_1    ... done
Creating audino_frontend_1 ... done
Creating audino_redis_1    ... done
Creating audino_backend_1  ... done
Creating audino_nginx_1    ... done
Attaching to audino_frontend_1, audino_redis_1, audino_mysql_1, audino_backend_1, audino_nginx_1
backend_1   | Connecting to database
backend_1   | Connected to database
redis_1     | 1:C 16 Jun 2020 04:41:38.290 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1     | 1:C 16 Jun 2020 04:41:38.290 # Redis version=5.0.8, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1     | 1:C 16 Jun 2020 04:41:38.290 # Configuration loaded
redis_1     | 1:M 16 Jun 2020 04:41:38.291 * Running mode=standalone, port=6379.
redis_1     | 1:M 16 Jun 2020 04:41:38.291 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1     | 1:M 16 Jun 2020 04:41:38.291 # Server initialized
redis_1     | 1:M 16 Jun 2020 04:41:38.291 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1     | 1:M 16 Jun 2020 04:41:38.291 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis_1     | 1:M 16 Jun 2020 04:41:38.291 * Ready to accept connections
mysql_1     | 2020-06-16 04:41:39+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.30-1debian10 started.
backend_1   | Applying new migrations
mysql_1     | 2020-06-16 04:41:39+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
backend_1   | INFO  [alembic.runtime.migration] Context impl MySQLImpl.
backend_1   | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
mysql_1     | 2020-06-16 04:41:39+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.30-1debian10 started.
audino_frontend_1 exited with code 0
mysql_1     | 2020-06-16T04:41:39.414481Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
mysql_1     | 2020-06-16T04:41:39.415488Z 0 [Note] mysqld (mysqld 5.7.30) starting as process 1 ...
backend_1   | INFO  [alembic.env] No changes in schema detected.
backend_1   | INFO  [alembic.runtime.migration] Context impl MySQLImpl.
backend_1   | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
backend_1   | Creating account for admin
backend_1   | Error creating admin user
backend_1   | (pymysql.err.IntegrityError) (1062, "Duplicate entry 'admin' for key 'ix_user_username'")
backend_1   | [SQL: INSERT INTO user (username, password, role_id, created_at, last_modified) VALUES (%(username)s, %(password)s, %(role_id)s, now(), now())]
backend_1   | [parameters: {'username': 'admin', 'password': 'pbkdf2:sha256:150000$nY5qCd1e$40793583a890c1364d76ec695f07de11734df7eaf3b200aacf54dc578cbac13f', 'role_id': 1}]
backend_1   | (Background on this error at: http://sqlalche.me/e/gkpj)
mysql_1     | 2020-06-16T04:41:39.417760Z 0 [Note] InnoDB: PUNCH HOLE support available
mysql_1     | 2020-06-16T04:41:39.417770Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
mysql_1     | 2020-06-16T04:41:39.417772Z 0 [Note] InnoDB: Uses event mutexes
mysql_1     | 2020-06-16T04:41:39.417789Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
mysql_1     | 2020-06-16T04:41:39.417791Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
mysql_1     | 2020-06-16T04:41:39.417793Z 0 [Note] InnoDB: Using Linux native AIO
mysql_1     | 2020-06-16T04:41:39.418010Z 0 [Note] InnoDB: Number of pools: 1
backend_1   | Starting flask production server
mysql_1     | 2020-06-16T04:41:39.418093Z 0 [Note] InnoDB: Using CPU crc32 instructions
mysql_1     | 2020-06-16T04:41:39.419253Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
backend_1   | [uWSGI] getting INI configuration from uwsgi.ini
mysql_1     | 2020-06-16T04:41:39.426966Z 0 [Note] InnoDB: Completed initialization of buffer pool
backend_1   | *** Starting uWSGI 2.0.18 (64bit) on [Tue Jun 16 04:41:43 2020] ***
backend_1   | compiled with version: 9.3.0 on 15 June 2020 07:12:27
backend_1   | os: Linux-4.15.0-99-generic #100~16.04.1-Ubuntu SMP Wed Apr 22 23:56:30 UTC 2020
backend_1   | nodename: 339a28d27448
backend_1   | machine: x86_64
backend_1   | clock source: unix
backend_1   | pcre jit disabled
backend_1   | detected number of CPU cores: 8
backend_1   | current working directory: /app
backend_1   | detected binary path: /usr/local/bin/uwsgi
backend_1   | uWSGI running as root, you can use --uid/--gid/--chroot options
backend_1   | *** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
backend_1   | your memory page size is 4096 bytes
backend_1   | detected max file descriptor number: 1048576
backend_1   | lock engine: pthread robust mutexes
mysql_1     | 2020-06-16T04:41:39.428352Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
mysql_1     | 2020-06-16T04:41:39.439611Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
backend_1   | thunder lock: disabled (you can enable it with --thunder-lock)
mysql_1     | 2020-06-16T04:41:39.608243Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
mysql_1     | 2020-06-16T04:41:39.608377Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
backend_1   | uWSGI http bound on 0.0.0.0:5000 fd 4
mysql_1     | 2020-06-16T04:41:39.875168Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
backend_1   | uwsgi socket 0 bound to TCP address 127.0.0.1:41919 (port auto-assigned) fd 3
backend_1   | uWSGI running as root, you can use --uid/--gid/--chroot options
backend_1   | *** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
mysql_1     | 2020-06-16T04:41:39.877303Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
mysql_1     | 2020-06-16T04:41:39.877339Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
backend_1   | Python version: 3.7.7 (default, Jun  3 2020, 19:58:28)  [GCC 9.3.0]
mysql_1     | 2020-06-16T04:41:39.878517Z 0 [Note] InnoDB: Waiting for purge to start
backend_1   | *** Python threads support is disabled. You can enable it with --enable-threads ***
backend_1   | Python main interpreter initialized at 0x560cb4372120
backend_1   | uWSGI running as root, you can use --uid/--gid/--chroot options
backend_1   | *** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
backend_1   | your server socket listen backlog is limited to 100 connections
backend_1   | your mercy for graceful operations on workers is 60 seconds
mysql_1     | 2020-06-16T04:41:39.928769Z 0 [Note] InnoDB: 5.7.30 started; log sequence number 12762037
mysql_1     | 2020-06-16T04:41:39.929238Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
mysql_1     | 2020-06-16T04:41:39.929779Z 0 [Note] Plugin 'FEDERATED' is disabled.
backend_1   | mapped 437424 bytes (427 KB) for 5 cores
mysql_1     | 2020-06-16T04:41:39.934353Z 0 [Note] InnoDB: Buffer pool(s) load completed at 200616  4:41:39
mysql_1     | 2020-06-16T04:41:39.937027Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
mysql_1     | 2020-06-16T04:41:39.937035Z 0 [Note] Skipping generation of SSL certificates as certificate files are present in data directory.
backend_1   | *** Operational MODE: preforking ***
mysql_1     | 2020-06-16T04:41:39.937482Z 0 [Warning] CA certificate ca.pem is self signed.
mysql_1     | 2020-06-16T04:41:39.937499Z 0 [Note] Skipping generation of RSA key pair as key files are present in data directory.
mysql_1     | 2020-06-16T04:41:39.937777Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
mysql_1     | 2020-06-16T04:41:39.937795Z 0 [Note] IPv6 is available.
mysql_1     | 2020-06-16T04:41:39.937801Z 0 [Note]   - '::' resolves to '::';
mysql_1     | 2020-06-16T04:41:39.937808Z 0 [Note] Server socket created on IP: '::'.
backend_1   | WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x560cb4372120 pid: 13 (default app)
backend_1   | uWSGI running as root, you can use --uid/--gid/--chroot options
backend_1   | *** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
backend_1   | *** uWSGI is running in multiple interpreter mode ***
backend_1   | spawned uWSGI master process (pid: 13)
mysql_1     | 2020-06-16T04:41:40.008325Z 0 [Warning] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
mysql_1     | 2020-06-16T04:41:40.017389Z 0 [Note] Event Scheduler: Loaded 0 events
backend_1   | spawned uWSGI worker 1 (pid: 14, cores: 1)
mysql_1     | 2020-06-16T04:41:40.017512Z 0 [Note] Execution of init_file '/mysql/create_database.sql' started.
backend_1   | spawned uWSGI worker 2 (pid: 15, cores: 1)
backend_1   | spawned uWSGI worker 3 (pid: 16, cores: 1)
mysql_1     | 2020-06-16T04:41:40.017795Z 0 [Note] Execution of init_file '/mysql/create_database.sql' ended.
mysql_1     | 2020-06-16T04:41:40.017861Z 0 [Note] mysqld: ready for connections.
mysql_1     | Version: '5.7.30'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
mysql_1     | 2020-06-16T04:41:42.198729Z 3 [Note] Aborted connection 3 to db: 'audino' user: 'audino' host: '172.30.0.4' (Got an error reading communication packets)
mysql_1     | 2020-06-16T04:41:43.798001Z 6 [Note] Aborted connection 6 to db: 'audino' user: 'audino' host: '172.30.0.4' (Got an error reading communication packets)
backend_1   | spawned uWSGI worker 4 (pid: 17, cores: 1)
backend_1   | spawned uWSGI worker 5 (pid: 18, cores: 1)
backend_1   | spawned uWSGI http 1 (pid: 19)
audino_nginx_1 exited with code 0
audino_backend_1 exited with code 137
mysql_1     | 2020-06-16T04:54:36.250373Z 0 [Note] Giving 0 client threads a chance to die gracefully
mysql_1     | 2020-06-16T04:54:36.250431Z 0 [Note] Shutting down slave threads
mysql_1     | 2020-06-16T04:54:36.250443Z 0 [Note] Forcefully disconnecting 0 remaining clients
mysql_1     | 2020-06-16T04:54:36.250454Z 0 [Note] Event Scheduler: Purging the queue. 0 events
mysql_1     | 2020-06-16T04:54:36.250572Z 0 [Note] Binlog end
mysql_1     | 2020-06-16T04:54:36.253728Z 0 [Note] Shutting down plugin 'ngram'
mysql_1     | 2020-06-16T04:54:36.253759Z 0 [Note] Shutting down plugin 'partition'
mysql_1     | 2020-06-16T04:54:36.253768Z 0 [Note] Shutting down plugin 'BLACKHOLE'
mysql_1     | 2020-06-16T04:54:36.253777Z 0 [Note] Shutting down plugin 'ARCHIVE'
mysql_1     | 2020-06-16T04:54:36.253783Z 0 [Note] Shutting down plugin 'PERFORMANCE_SCHEMA'
mysql_1     | 2020-06-16T04:54:36.253849Z 0 [Note] Shutting down plugin 'MRG_MYISAM'
mysql_1     | 2020-06-16T04:54:36.253867Z 0 [Note] Shutting down plugin 'MyISAM'
mysql_1     | 2020-06-16T04:54:36.253890Z 0 [Note] Shutting down plugin 'INNODB_SYS_VIRTUAL'
mysql_1     | 2020-06-16T04:54:36.253908Z 0 [Note] Shutting down plugin 'INNODB_SYS_DATAFILES'
mysql_1     | 2020-06-16T04:54:36.253918Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLESPACES'
mysql_1     | 2020-06-16T04:54:36.253928Z 0 [Note] Shutting down plugin 'INNODB_SYS_FOREIGN_COLS'
mysql_1     | 2020-06-16T04:54:36.253938Z 0 [Note] Shutting down plugin 'INNODB_SYS_FOREIGN'
mysql_1     | 2020-06-16T04:54:36.253947Z 0 [Note] Shutting down plugin 'INNODB_SYS_FIELDS'
mysql_1     | 2020-06-16T04:54:36.253956Z 0 [Note] Shutting down plugin 'INNODB_SYS_COLUMNS'
mysql_1     | 2020-06-16T04:54:36.253965Z 0 [Note] Shutting down plugin 'INNODB_SYS_INDEXES'
mysql_1     | 2020-06-16T04:54:36.253976Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLESTATS'
mysql_1     | 2020-06-16T04:54:36.253987Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLES'
mysql_1     | 2020-06-16T04:54:36.253997Z 0 [Note] Shutting down plugin 'INNODB_FT_INDEX_TABLE'
mysql_1     | 2020-06-16T04:54:36.254007Z 0 [Note] Shutting down plugin 'INNODB_FT_INDEX_CACHE'
mysql_1     | 2020-06-16T04:54:36.254017Z 0 [Note] Shutting down plugin 'INNODB_FT_CONFIG'
mysql_1     | 2020-06-16T04:54:36.254027Z 0 [Note] Shutting down plugin 'INNODB_FT_BEING_DELETED'
mysql_1     | 2020-06-16T04:54:36.254036Z 0 [Note] Shutting down plugin 'INNODB_FT_DELETED'
mysql_1     | 2020-06-16T04:54:36.254045Z 0 [Note] Shutting down plugin 'INNODB_FT_DEFAULT_STOPWORD'
mysql_1     | 2020-06-16T04:54:36.254055Z 0 [Note] Shutting down plugin 'INNODB_METRICS'
mysql_1     | 2020-06-16T04:54:36.254065Z 0 [Note] Shutting down plugin 'INNODB_TEMP_TABLE_INFO'
mysql_1     | 2020-06-16T04:54:36.254075Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_POOL_STATS'
mysql_1     | 2020-06-16T04:54:36.254086Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_PAGE_LRU'
mysql_1     | 2020-06-16T04:54:36.254095Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_PAGE'
mysql_1     | 2020-06-16T04:54:36.254106Z 0 [Note] Shutting down plugin 'INNODB_CMP_PER_INDEX_RESET'
mysql_1     | 2020-06-16T04:54:36.254117Z 0 [Note] Shutting down plugin 'INNODB_CMP_PER_INDEX'
mysql_1     | 2020-06-16T04:54:36.254127Z 0 [Note] Shutting down plugin 'INNODB_CMPMEM_RESET'
mysql_1     | 2020-06-16T04:54:36.254137Z 0 [Note] Shutting down plugin 'INNODB_CMPMEM'
mysql_1     | 2020-06-16T04:54:36.254147Z 0 [Note] Shutting down plugin 'INNODB_CMP_RESET'
mysql_1     | 2020-06-16T04:54:36.254158Z 0 [Note] Shutting down plugin 'INNODB_CMP'
mysql_1     | 2020-06-16T04:54:36.254168Z 0 [Note] Shutting down plugin 'INNODB_LOCK_WAITS'
mysql_1     | 2020-06-16T04:54:36.254177Z 0 [Note] Shutting down plugin 'INNODB_LOCKS'
mysql_1     | 2020-06-16T04:54:36.254188Z 0 [Note] Shutting down plugin 'INNODB_TRX'
mysql_1     | 2020-06-16T04:54:36.254198Z 0 [Note] Shutting down plugin 'InnoDB'
mysql_1     | 2020-06-16T04:54:36.254305Z 0 [Note] InnoDB: FTS optimize thread exiting.
mysql_1     | 2020-06-16T04:54:36.254482Z 0 [Note] InnoDB: Starting shutdown...
redis_1     | 1:signal-handler (1592283276) Received SIGTERM scheduling shutdown...
redis_1     | 1:M 16 Jun 2020 04:54:36.349 # User requested shutdown...
redis_1     | 1:M 16 Jun 2020 04:54:36.349 # Redis is now ready to exit, bye bye...
mysql_1     | 2020-06-16T04:54:36.354992Z 0 [Note] InnoDB: Dumping buffer pool(s) to /var/lib/mysql/ib_buffer_pool
mysql_1     | 2020-06-16T04:54:36.355656Z 0 [Note] InnoDB: Buffer pool(s) dump completed at 200616  4:54:36
audino_redis_1 exited with code 0
mysql_1     | 2020-06-16T04:54:37.434187Z 0 [Note] InnoDB: Shutdown completed; log sequence number 12762388
mysql_1     | 2020-06-16T04:54:37.435575Z 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
mysql_1     | 2020-06-16T04:54:37.435599Z 0 [Note] Shutting down plugin 'MEMORY'
mysql_1     | 2020-06-16T04:54:37.435602Z 0 [Note] Shutting down plugin 'CSV'
mysql_1     | 2020-06-16T04:54:37.435605Z 0 [Note] Shutting down plugin 'sha256_password'
mysql_1     | 2020-06-16T04:54:37.435607Z 0 [Note] Shutting down plugin 'mysql_native_password'
mysql_1     | 2020-06-16T04:54:37.435688Z 0 [Note] Shutting down plugin 'binlog'
mysql_1     | 2020-06-16T04:54:37.436572Z 0 [Note] mysqld: Shutdown complete
mysql_1     | 
audino_mysql_1 exited with code 0
anushree@tellinux008:~/Documents/MC/TASK1/audino$ docker-compose -f docker-compose.prod.yml up
Creating network "audino_default" with the default driver
Creating network "audino_backend-network" with the default driver
Creating network "audino_frontend-network" with the default driver
Creating audino_redis_1    ... done
Creating audino_frontend_1 ... done
Creating audino_mysql_1    ... done
Creating audino_backend_1  ... done
Creating audino_nginx_1    ... done
Attaching to audino_frontend_1, audino_redis_1, audino_mysql_1, audino_backend_1, audino_nginx_1
backend_1   | Connecting to database
backend_1   | Connected to database
backend_1   | Applying new migrations
backend_1   | INFO  [alembic.runtime.migration] Context impl MySQLImpl.
backend_1   | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
backend_1   | INFO  [alembic.env] No changes in schema detected.
audino_frontend_1 exited with code 0
mysql_1     | 2020-06-16 04:58:24+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.30-1debian10 started.
backend_1   | INFO  [alembic.runtime.migration] Context impl MySQLImpl.
backend_1   | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
backend_1   | Creating account for admin
backend_1   | Error creating admin user
backend_1   | (pymysql.err.IntegrityError) (1062, "Duplicate entry 'admin' for key 'ix_user_username'")
backend_1   | [SQL: INSERT INTO user (username, password, role_id, created_at, last_modified) VALUES (%(username)s, %(password)s, %(role_id)s, now(), now())]
backend_1   | [parameters: {'username': 'admin', 'password': 'pbkdf2:sha256:150000$QqaVhJ4N$f3512574b4b1f0bd04a4ff63e8befebb313e8c5aa76e79aa6abcfcd391215210', 'role_id': 1}]
backend_1   | (Background on this error at: http://sqlalche.me/e/gkpj)
mysql_1     | 2020-06-16 04:58:24+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
redis_1     | 1:C 16 Jun 2020 04:58:23.530 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1     | 1:C 16 Jun 2020 04:58:23.530 # Redis version=5.0.8, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1     | 1:C 16 Jun 2020 04:58:23.530 # Configuration loaded
mysql_1     | 2020-06-16 04:58:24+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.30-1debian10 started.
backend_1   | Starting flask production server
mysql_1     | 2020-06-16T04:58:24.634653Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
mysql_1     | 2020-06-16T04:58:24.635666Z 0 [Note] mysqld (mysqld 5.7.30) starting as process 1 ...
mysql_1     | 2020-06-16T04:58:24.637808Z 0 [Note] InnoDB: PUNCH HOLE support available
mysql_1     | 2020-06-16T04:58:24.637817Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
mysql_1     | 2020-06-16T04:58:24.637834Z 0 [Note] InnoDB: Uses event mutexes
mysql_1     | 2020-06-16T04:58:24.637837Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
mysql_1     | 2020-06-16T04:58:24.637838Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
mysql_1     | 2020-06-16T04:58:24.637840Z 0 [Note] InnoDB: Using Linux native AIO
redis_1     | 1:M 16 Jun 2020 04:58:23.531 * Running mode=standalone, port=6379.
backend_1   | [uWSGI] getting INI configuration from uwsgi.ini
backend_1   | *** Starting uWSGI 2.0.18 (64bit) on [Tue Jun 16 04:58:29 2020] ***
backend_1   | compiled with version: 9.3.0 on 15 June 2020 07:12:27
backend_1   | os: Linux-4.15.0-99-generic #100~16.04.1-Ubuntu SMP Wed Apr 22 23:56:30 UTC 2020
backend_1   | nodename: 51b97d95cf3d
backend_1   | machine: x86_64
backend_1   | clock source: unix
backend_1   | pcre jit disabled
backend_1   | detected number of CPU cores: 8
backend_1   | current working directory: /app
backend_1   | detected binary path: /usr/local/bin/uwsgi
backend_1   | uWSGI running as root, you can use --uid/--gid/--chroot options
backend_1   | *** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
backend_1   | your memory page size is 4096 bytes
backend_1   | detected max file descriptor number: 1048576
backend_1   | lock engine: pthread robust mutexes
redis_1     | 1:M 16 Jun 2020 04:58:23.531 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
backend_1   | thunder lock: disabled (you can enable it with --thunder-lock)
redis_1     | 1:M 16 Jun 2020 04:58:23.531 # Server initialized
mysql_1     | 2020-06-16T04:58:24.638053Z 0 [Note] InnoDB: Number of pools: 1
backend_1   | uWSGI http bound on 0.0.0.0:5000 fd 4
backend_1   | uwsgi socket 0 bound to TCP address 127.0.0.1:42615 (port auto-assigned) fd 3
backend_1   | uWSGI running as root, you can use --uid/--gid/--chroot options
backend_1   | *** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
redis_1     | 1:M 16 Jun 2020 04:58:23.531 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1     | 1:M 16 Jun 2020 04:58:23.531 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis_1     | 1:M 16 Jun 2020 04:58:23.531 * Ready to accept connections
backend_1   | Python version: 3.7.7 (default, Jun  3 2020, 19:58:28)  [GCC 9.3.0]
mysql_1     | 2020-06-16T04:58:24.638135Z 0 [Note] InnoDB: Using CPU crc32 instructions
backend_1   | *** Python threads support is disabled. You can enable it with --enable-threads ***
backend_1   | Python main interpreter initialized at 0x55d3a87f5120
backend_1   | uWSGI running as root, you can use --uid/--gid/--chroot options
backend_1   | *** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
backend_1   | your server socket listen backlog is limited to 100 connections
backend_1   | your mercy for graceful operations on workers is 60 seconds
backend_1   | mapped 437424 bytes (427 KB) for 5 cores
mysql_1     | 2020-06-16T04:58:24.639279Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
backend_1   | *** Operational MODE: preforking ***
mysql_1     | 2020-06-16T04:58:24.647154Z 0 [Note] InnoDB: Completed initialization of buffer pool
mysql_1     | 2020-06-16T04:58:24.648619Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
backend_1   | WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x55d3a87f5120 pid: 12 (default app)
backend_1   | uWSGI running as root, you can use --uid/--gid/--chroot options
backend_1   | *** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
backend_1   | *** uWSGI is running in multiple interpreter mode ***
backend_1   | spawned uWSGI master process (pid: 12)
backend_1   | spawned uWSGI worker 1 (pid: 13, cores: 1)
mysql_1     | 2020-06-16T04:58:24.659872Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
backend_1   | spawned uWSGI worker 2 (pid: 14, cores: 1)
mysql_1     | 2020-06-16T04:58:24.770185Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
mysql_1     | 2020-06-16T04:58:24.770338Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
backend_1   | spawned uWSGI worker 3 (pid: 15, cores: 1)
backend_1   | spawned uWSGI worker 4 (pid: 16, cores: 1)
mysql_1     | 2020-06-16T04:58:24.987938Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
backend_1   | spawned uWSGI worker 5 (pid: 17, cores: 1)
mysql_1     | 2020-06-16T04:58:24.989861Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
mysql_1     | 2020-06-16T04:58:24.989891Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
backend_1   | spawned uWSGI http 1 (pid: 18)
mysql_1     | 2020-06-16T04:58:24.990602Z 0 [Note] InnoDB: Waiting for purge to start
mysql_1     | 2020-06-16T04:58:25.041009Z 0 [Note] InnoDB: 5.7.30 started; log sequence number 12762388
mysql_1     | 2020-06-16T04:58:25.041490Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
mysql_1     | 2020-06-16T04:58:25.042072Z 0 [Note] Plugin 'FEDERATED' is disabled.
mysql_1     | 2020-06-16T04:58:25.047035Z 0 [Note] InnoDB: Buffer pool(s) load completed at 200616  4:58:25
mysql_1     | 2020-06-16T04:58:25.058773Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
mysql_1     | 2020-06-16T04:58:25.058805Z 0 [Note] Skipping generation of SSL certificates as certificate files are present in data directory.
mysql_1     | 2020-06-16T04:58:25.061015Z 0 [Warning] CA certificate ca.pem is self signed.
mysql_1     | 2020-06-16T04:58:25.061103Z 0 [Note] Skipping generation of RSA key pair as key files are present in data directory.
mysql_1     | 2020-06-16T04:58:25.062364Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
mysql_1     | 2020-06-16T04:58:25.062435Z 0 [Note] IPv6 is available.
mysql_1     | 2020-06-16T04:58:25.062463Z 0 [Note]   - '::' resolves to '::';
mysql_1     | 2020-06-16T04:58:25.062495Z 0 [Note] Server socket created on IP: '::'.
mysql_1     | 2020-06-16T04:58:25.248089Z 0 [Warning] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
mysql_1     | 2020-06-16T04:58:25.253209Z 0 [Note] Event Scheduler: Loaded 0 events
mysql_1     | 2020-06-16T04:58:25.253356Z 0 [Note] Execution of init_file '/mysql/create_database.sql' started.
mysql_1     | 2020-06-16T04:58:25.253575Z 0 [Note] Execution of init_file '/mysql/create_database.sql' ended.
mysql_1     | 2020-06-16T04:58:25.253627Z 0 [Note] mysqld: ready for connections.
mysql_1     | Version: '5.7.30'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
mysql_1     | 2020-06-16T04:58:27.336815Z 3 [Note] Aborted connection 3 to db: 'audino' user: 'audino' host: '192.168.16.4' (Got an error reading communication packets)
mysql_1     | 2020-06-16T04:58:29.118351Z 6 [Note] Aborted connection 6 to db: 'audino' user: 'audino' host: '192.168.16.4' (Got an error reading communication packets)

**Comment by manrajgrover** [comment]
@anu308 Thanks for reporting! Kindly share your `docker-compose.prod.yml` file

**Comment by anu308** [comment]
Here is the file.[docker-compose.prod.yml.zip](https://github.com/midas-research/audino/files/4791991/docker-compose.prod.yml.zip)

**Comment by manrajgrover** [comment]
@anu308 Please change line 30-31 to:

```
ports:
    - 7000:80
```

**Comment by manrajgrover** [comment]
@anu308 Kindly let me know if this is fixed.

**Comment by manrajgrover** [comment]
Closing this assuming this has been fixed. If not, please reopen the issue.
