### ISSUE TITLE
is_marked_for_review always False

### ISSUE THREAD

**Issue by bcartign** [midas-research/audino#37]
When uploading data, marked_review is always False.

There seems to be a typo in backend/route/data.py line 45 should be 
is_marked_for_review = bool(request.form.get("*marked_review*", False))
or 
upload_data/upload_data.py   and  docs/tutorials/upload-data.md
should be corrected with *is_marked_for_review* instead of marked_review
or am I wrong ?

**Comment by manrajgrover** [comment]
Hi @bcartign,

Thanks for reporting the bug! I've fixed it in PR #38.

The example in documentation as well as script was wrong. 

Could you take a look and let me know if it is fixed?

**Comment by bcartign** [comment]
OK Great. That's correct. Thanks.
Just another typo, the link in _docs/tutorials/upload-data.md_  shoud have an extra 's',  should be : 
https://github.com/midas-research/audino/blob/master/examples/upload_data/upload_data.py
instead of 
https://github.com/midas-research/audino/blob/master/example/upload_data/upload_data.py

**Comment by manrajgrover** [comment]
@bcartign Thanks for reporting! I've fixed it in 3de7bc9de592b2ceb897b8c3846a3f8ecb68c89e
