### ISSUE TITLE
Unable to view application in browser

### ISSUE THREAD

**Issue by Mounika2405** [midas-research/audino#60]
Hi,
After bringing the services up http://0.0.0.0 says the site can't be reached. Please help me fix this issue.

Command used: docker-compose -f docker-compose.prod.yml up

Starting audino_redis_1    ... done
Starting audino_mysql_1    ... done
Starting audino_frontend_1 ... done
Starting audino_backend_1  ... done
Recreating audino_nginx_1  ... done
Attaching to audino_redis_1, audino_frontend_1, audino_mysql_1, audino_backend_1, audino_nginx_1
mysql_1     | 2020-09-22 16:30:11+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.31-1debian10 started.
mysql_1     | 2020-09-22 16:30:11+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
redis_1     | 1:C 22 Sep 2020 16:30:11.272 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1     | 1:C 22 Sep 2020 16:30:11.272 # Redis version=5.0.8, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1     | 1:C 22 Sep 2020 16:30:11.272 # Configuration loaded
redis_1     | 1:M 22 Sep 2020 16:30:11.274 * Running mode=standalone, port=6379.
audino_frontend_1 exited with code 0
redis_1     | 1:M 22 Sep 2020 16:30:11.275 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1     | 1:M 22 Sep 2020 16:30:11.275 # Server initialized
redis_1     | 1:M 22 Sep 2020 16:30:11.275 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
backend_1   | Connecting to database
mysql_1     | 2020-09-22 16:30:11+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.31-1debian10 started.
mysql_1     | 2020-09-22T16:30:12.291032Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
mysql_1     | 2020-09-22T16:30:12.293497Z 0 [Note] mysqld (mysqld 5.7.31) starting as process 1 ...
mysql_1     | 2020-09-22T16:30:12.297751Z 0 [Note] InnoDB: PUNCH HOLE support available
mysql_1     | 2020-09-22T16:30:12.297974Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
mysql_1     | 2020-09-22T16:30:12.298175Z 0 [Note] InnoDB: Uses event mutexes
mysql_1     | 2020-09-22T16:30:12.298307Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
mysql_1     | 2020-09-22T16:30:12.298438Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
mysql_1     | 2020-09-22T16:30:12.298567Z 0 [Note] InnoDB: Using Linux native AIO
mysql_1     | 2020-09-22T16:30:12.299886Z 0 [Note] InnoDB: Number of pools: 1
mysql_1     | 2020-09-22T16:30:12.302156Z 0 [Note] InnoDB: Using CPU crc32 instructions
mysql_1     | 2020-09-22T16:30:12.305290Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
mysql_1     | 2020-09-22T16:30:12.320483Z 0 [Note] InnoDB: Completed initialization of buffer pool
mysql_1     | 2020-09-22T16:30:12.325605Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
mysql_1     | 2020-09-22T16:30:12.344124Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
mysql_1     | 2020-09-22T16:30:12.384258Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
mysql_1     | 2020-09-22T16:30:12.384701Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
mysql_1     | 2020-09-22T16:30:12.411574Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
mysql_1     | 2020-09-22T16:30:12.412574Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
mysql_1     | 2020-09-22T16:30:12.412696Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
mysql_1     | 2020-09-22T16:30:12.413252Z 0 [Note] InnoDB: Waiting for purge to start
mysql_1     | 2020-09-22T16:30:12.463639Z 0 [Note] InnoDB: 5.7.31 started; log sequence number 12852515
mysql_1     | 2020-09-22T16:30:12.464479Z 0 [Note] Plugin 'FEDERATED' is disabled.
mysql_1     | 2020-09-22T16:30:12.464863Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
mysql_1     | 2020-09-22T16:30:12.502210Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
mysql_1     | 2020-09-22T16:30:12.502654Z 0 [Note] Skipping generation of SSL certificates as certificate files are present in data directory.
mysql_1     | 2020-09-22T16:30:12.506530Z 0 [Warning] CA certificate ca.pem is self signed.
mysql_1     | 2020-09-22T16:30:12.507453Z 0 [Note] Skipping generation of RSA key pair as key files are present in data directory.
mysql_1     | 2020-09-22T16:30:12.510383Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
mysql_1     | 2020-09-22T16:30:12.510881Z 0 [Note] IPv6 is available.
mysql_1     | 2020-09-22T16:30:12.511185Z 0 [Note]   - '::' resolves to '::';
mysql_1     | 2020-09-22T16:30:12.513471Z 0 [Note] Server socket created on IP: '::'.
mysql_1     | 2020-09-22T16:30:12.516365Z 0 [Warning] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
mysql_1     | 2020-09-22T16:30:12.524127Z 0 [Note] InnoDB: Buffer pool(s) load completed at 200922 16:30:12
mysql_1     | 2020-09-22T16:30:12.562397Z 0 [Note] Event Scheduler: Loaded 0 events
mysql_1     | 2020-09-22T16:30:12.562793Z 0 [Note] Execution of init_file '/mysql/create_database.sql' started.
mysql_1     | 2020-09-22T16:30:12.566627Z 0 [Note] Execution of init_file '/mysql/create_database.sql' ended.
backend_1   | Couldn't connect to MySQL: 0/30
mysql_1     | 2020-09-22T16:30:12.566910Z 0 [Note] mysqld: ready for connections.
mysql_1     | Version: '5.7.31'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
backend_1   | Connected to database
backend_1   | Applying new migrations
backend_1   | INFO  [alembic.runtime.migration] Context impl MySQLImpl.
backend_1   | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
backend_1   | INFO  [alembic.env] No changes in schema detected.
backend_1   | INFO  [alembic.runtime.migration] Context impl MySQLImpl.
backend_1   | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
mysql_1     | 2020-09-22T16:30:17.321763Z 3 [Note] Aborted connection 3 to db: 'audino' user: 'audino' host: '192.168.192.4' (Got an error reading communication packets)
backend_1   | Creating account for admin
backend_1   | Error creating admin user
backend_1   | (pymysql.err.IntegrityError) (1062, "Duplicate entry 'admin' for key 'ix_user_username'")
backend_1   | [SQL: INSERT INTO user (username, password, role_id, created_at, last_modified) VALUES (%(username)s, %(password)s, %(role_id)s, now(), now())]
backend_1   | [parameters: {'username': 'admin', 'password': 'pbkdf2:sha256:150000$nZz4O4ZL$da08ee4cd9683e9cdb9a571c60e8670f10801b2bfc207644d5f1ebb68c1cabfd', 'role_id': 1}]
backend_1   | (Background on this error at: http://sqlalche.me/e/gkpj)
backend_1   | Starting flask production server
backend_1   | [uWSGI] getting INI configuration from uwsgi.ini
backend_1   | *** Starting uWSGI 2.0.18 (64bit) on [Tue Sep 22 16:30:19 2020] ***
backend_1   | compiled with version: 9.3.0 on 22 September 2020 09:56:14
backend_1   | os: Linux-4.19.130-boot2docker #1 SMP Mon Jun 29 23:52:55 UTC 2020
backend_1   | nodename: 38262ddbfafa
backend_1   | machine: x86_64
backend_1   | clock source: unix
backend_1   | pcre jit disabled
backend_1   | detected number of CPU cores: 1
backend_1   | current working directory: /app
backend_1   | detected binary path: /usr/local/bin/uwsgi
backend_1   | uWSGI running as root, you can use --uid/--gid/--chroot options
backend_1   | *** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
backend_1   | your memory page size is 4096 bytes
backend_1   | detected max file descriptor number: 1048576
backend_1   | lock engine: pthread robust mutexes
backend_1   | thunder lock: disabled (you can enable it with --thunder-lock)
backend_1   | uWSGI http bound on 0.0.0.0:5000 fd 4
backend_1   | uwsgi socket 0 bound to TCP address 127.0.0.1:45089 (port auto-assigned) fd 3
backend_1   | uWSGI running as root, you can use --uid/--gid/--chroot options
backend_1   | *** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
backend_1   | Python version: 3.7.9 (default, Aug 18 2020, 04:02:05)  [GCC 9.3.0]
backend_1   | *** Python threads support is disabled. You can enable it with --enable-threads ***
backend_1   | Python main interpreter initialized at 0x55b1984ee100
backend_1   | uWSGI running as root, you can use --uid/--gid/--chroot options
backend_1   | *** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
backend_1   | your server socket listen backlog is limited to 100 connections
backend_1   | your mercy for graceful operations on workers is 60 seconds
backend_1   | mapped 437424 bytes (427 KB) for 5 cores
backend_1   | *** Operational MODE: preforking ***
backend_1   | WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x55b1984ee100 pid: 12 (default app)
backend_1   | uWSGI running as root, you can use --uid/--gid/--chroot options
backend_1   | *** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
backend_1   | *** uWSGI is running in multiple interpreter mode ***
backend_1   | spawned uWSGI master process (pid: 12)
backend_1   | spawned uWSGI worker 1 (pid: 13, cores: 1)
backend_1   | spawned uWSGI worker 2 (pid: 14, cores: 1)
backend_1   | spawned uWSGI worker 3 (pid: 15, cores: 1)
backend_1   | spawned uWSGI worker 4 (pid: 16, cores: 1)
backend_1   | spawned uWSGI worker 5 (pid: 17, cores: 1)

**Comment by manrajgrover** [comment]
@Mounika2405 Hi, were you able to resolve this issue?

**Comment by Mounika2405** [comment]
@manrajgrover Hi, I was unable to resolve the issue. It would be great if you could help.

**Comment by manrajgrover** [comment]
@Mounika2405 According to the logs, it should be working.

Can you share how the tool is being served? Is it running on a cloud server or local machine?
If it is running on a cloud server, can you check if the required ports are being mapped?

**Comment by manrajgrover** [comment]
@Mounika2405 Please let me know if the issue was fixed. Thanks in advance!

**Comment by manrajgrover** [comment]
@Mounika2405 Closing this as stale issue. If the problem persists, please comment and I will reopen the issue.
