### ISSUE TITLE
MySQL fails to initialize on startup

### ISSUE THREAD

**Issue by wuxiaobo** [midas-research/audino#63]
Starting audino_redis_1    ... done
Starting audino_mysql_1    ... done
Starting audino_frontend_1 ... done
Starting audino_backend_1  ... done
Starting audino_nginx_1    ... done
Attaching to audino_redis_1, audino_frontend_1, audino_mysql_1, audino_backend_1, audino_nginx_1
backend_1   | Connecting to database
redis_1     | 1:C 04 Jan 2021 09:22:07.781 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1     | 1:C 04 Jan 2021 09:22:07.781 # Redis version=5.0.8, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1     | 1:C 04 Jan 2021 09:22:07.781 # Configuration loaded
mysql_1     | 2021-01-04 09:22:07+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.32-1debian10 started.
mysql_1     | 2021-01-04 09:22:08+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
mysql_1     | 2021-01-04 09:22:08+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.32-1debian10 started.
mysql_1     | 2021-01-04 09:22:08+00:00 [Note] [Entrypoint]: Initializing database files
mysql_1     | 2021-01-04T09:22:08.380664Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
mysql_1     | 2021-01-04T09:22:08.383814Z 0 [ERROR] --initialize specified but the data directory has files in it. Aborting.
mysql_1     | 2021-01-04T09:22:08.383986Z 0 [ERROR] Aborting
mysql_1     | 
redis_1     | 1:M 04 Jan 2021 09:22:07.788 * Running mode=standalone, port=6379.
redis_1     | 1:M 04 Jan 2021 09:22:07.788 # Server initialized
redis_1     | 1:M 04 Jan 2021 09:22:07.788 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis_1     | 1:M 04 Jan 2021 09:22:07.788 * Ready to accept connections
audino_frontend_1 exited with code 0
audino_mysql_1 exited with code 1
backend_1   | Couldn't connect to MySQL: 0/30
backend_1   | Couldn't connect to MySQL: 1/30
backend_1   | Couldn't connect to MySQL: 2/30
^CGracefully stopping... (press Ctrl+C again to force)
Stopping audino_nginx_1    ... done
Stopping audino_backend_1  ... done
Stopping audino_redis_1    ... done

**Comment by wuxiaobo** [comment]
audino_mysql_1 exited with code 1
backend_1   | Couldn't connect to MySQL: 0/30
backend_1   | Couldn't connect to MySQL: 1/30
backend_1   | Couldn't connect to MySQL: 2/30

**Comment by manrajgrover** [comment]
@wuxiaobo Thanks for reporting the issue! It seems like `mysql_prod_data` volume is not empty, which is why MySQL is not working. A quick fix would be to delete the `mysql_prod_data` volume. **Warning**: This would delete the contents of MySQL database, and hence the annotation projects.

I believe permanent fix would be to initialize database conditionally. But to conclude the same, I would need the content of your `docker-compose.prod.yml` file. Please share the same.

**Comment by manrajgrover** [comment]
On second thoughts, it looks like the data volume mounted for `mysql` seems to have content which is preventing MySQL to initialize. Please check if you have mounted a directory that already contains content or not.

> I believe permanent fix would be to initialize database conditionally.
MySQL docker handles this internally.

**Comment by manrajgrover** [comment]
@wuxiaobo Any updates here?

**Comment by manrajgrover** [comment]
@wuxiaobo I'm considering this as fixed. If not, please reopen the issue.

**Comment by wuxiaobo** [comment]
ok Problem solved
