### ISSUE TITLE
Annotation section is not showing

### ISSUE THREAD

**Issue by drctoday** [midas-research/audino#86]
Hi Midas team,

We have successfully installed and deployed the tool, created projects, assigned users , created labels (and their values) assigned to the project. However, when both users (admin or normal) navigate to Projects / Data and click on the audio file under Yet to annotate, the only available section is the preview part. Where is the annotation section?
![no_annotate_section](https://user-images.githubusercontent.com/90763976/134569090-49cf4ef5-62ca-469e-87e4-dd1d6ab1a6a5.png)

We deployed the tool on Linux.

**Comment by manrajgrover** [comment]
Hi @drctoday, the annotation section appears when you mark a temporal segment on the audio. Once the temporal segment is marked, click on it to reveal the annotation section.

**Comment by manrajgrover** [comment]
Please let me know if more information is required.

**Comment by rupali-das** [comment]
> Hi @drctoday, the annotation section appears when you mark a temporal segment on the audio. Once the temporal segment is marked, click on it to reveal the annotation section.

Hi, Can you let me know how to add the temporal segment.
